### ISSUE TITLE
Determine the production url for the CASS application

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CompetencyFrameworks#14]
The site URL is stored with a framework competency. If the content is moved to a new domain, the contents would likely have to be updated to the new URL.
The current working domain is:
[http://cass.credentialfinder.net](url)

What should be used as the public domain for CASS?

**Comment by stuartasutton** [comment]
@cwd-mparsons, I thought that it had been settled we'd use the same base URI as the credential registry with the following namespaces:

```
http://credentialEngineRegistry.org/resources/ce-[uuid] 
     (credentials & related entities)
http://credentialEngineRegistry.org/competencies/[uuid] 
     (competency frameworks)
http://credentialEngineRegistry.org/concepts/[uuid] 
     (concept schemes)
```
This would tie them all together in terms of branding.
