### ISSUE TITLE
Process for importing from spreadsheets

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#15]
Using http://cass.credentialfinder.net I attempted to test/try out the spreadsheet bulk upload mechanism using the two sheets in this document: https://docs.google.com/spreadsheets/d/1lryfiYKQjOLw61zzC17rv0NWBYuch1b2GnUb81-8v44/edit#gid=0

It correctly detected the column names and I assigned them appropriately, but the result was not correct:
![image](https://user-images.githubusercontent.com/21346519/27500859-e26f3922-582f-11e7-97bc-826755d08e5d.png)

Any ideas on what I may have done wrong?

**Comment by Lomilar** [comment]
IDs must contain alpha or symbol characters in the unique identifier segments.
The URLs do not point at an existing repository endpoint.

Valid urls for IDs would look like: http://cass.credentialengine.net/api/custom/data/competency-1

You can omit the endpoint for the URL. e.g. "competency-1" will be expanded with the endpoint automatically.

I edited the spreadsheet into to a usable form.

**Comment by siuc-nate** [comment]
We tried this when we were in that webinar and it worked right away - did you have any luck figuring out what may have happened?
