### ISSUE TITLE
Error importing ASN standards

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#16]
I attempted to import the standards using the JSON document from here: http://asn.jesandco.org/resources/D10003FB/Info

It appeared to work, at first (the list of tasks remaining appeared and ticked down to zero), but after that, no framework was displayed.  I waited a bit, refreshed a few times, just to be sure, but no luck.

If you attempt to import those standards, do you see any errors on your end? Is there logging of some sort I could investigate to solve problems like this in the future?  Thanks.

**Comment by Lomilar** [comment]
Which tool did you use? The CASS Manager or "Manage Competency Frameworks"?

If using the CASS Manager, after the import is complete, IIRC, you have to be sure to manually save the framework.

For 0.2, I would recommend avoiding use of the CASS Manager. It has many such 'gotchas'.

**Comment by siuc-nate** [comment]
I used this option:
![image](https://user-images.githubusercontent.com/21346519/27543968-610828d4-5a51-11e7-888c-b87048b92d84.png)

**Comment by Lomilar** [comment]
I imported the same framework without issue.

It _does_ take a decent amount of time for all of the execution to finish, even after the "tasks remaining" has ticked down to 0. If you refreshed before it was complete, I could see it having not saved the framework.

cassproject/CASS#22

**Comment by siuc-nate** [comment]
We waited some time (I figured there might be some post-processing involved) and it never showed - in fact, I still don't see it.  I only see Test Framework 1, as in the screenshot above.

**Comment by siuc-nate** [comment]
I do get a number of errors:
![image](https://user-images.githubusercontent.com/21346519/27595216-aa20e88c-5b21-11e7-95de-ce39921e115d.png)

Would any of those files be related to the issue above?

**Comment by Lomilar** [comment]
Those ones are not, those are various scripts searching for other script files.
