### ISSUE TITLE
Search API

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/CompetencyFrameworks#18]
@siuc-nate is using the search API provided by @Lomilar .  This search should be available to app developers who may want to develop tools that incorporate the search. For example, we're developing an app for Talent Pipeline Management.  The app uses competency statements and frameworks to develop surveys of employer collaboratives.  We want to search for statements and frameworks and be able to save them in the statements and or any statements in frameworks.

**Comment by Lomilar** [comment]
@siuc-nate Is this going to be using the same stack you use for Workit? (.NET Web Application)

This search capability exists in CASS, I will be adding additional documentation to the developer's guide that should cover this use case.

I welcome additional questions.

**Comment by siuc-nate** [comment]
See issue #11
