### ISSUE TITLE
Avoiding Duplication of Frameworks

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/CompetencyFrameworks#19]
There is a great deal of potential to end up with duplicated competency statements and entire frameworks.  When new competency statement or framework is added via any of the upload, import, API options, what is being done to check for existing statements and frameworks to avoid duplicates? I included @siuc-nate because we discussed adding this issue.

**Comment by Lomilar** [comment]
The current tools available with the UI do not check for duplicates.

The script provided that does the framework import from the Workit CSV Export _does_ check for, and reuse duplicates.

This issue warrants some discussion, as the reuse of competency statements can pose some governance issues, as often competencies in practice are contextualized by the framework they appear in. e.g. some frameworks highly specific to say, a credential, can include statements like "can perform work duties" that are highly contextual. These competencies should not be reused, but competencies that state "can add two digit numbers" should.

**Comment by jkitchensSIUC** [comment]
Can mechanisms that help prevent duplication be built in, start with the source URL and other checks for matches.  It is reasonable to expect large parts of frameworks to be reused by others.  Such remixes and/or derivatives should be allowed.

Should exact duplicates, be branded as a derivatives?

**Comment by siuc-nate** [comment]
Based on our 6/28/2017 conversation:
- Duplicates are acceptable, but should be discouraged
   - When a user attempts to create a framework, they should be prompted to include the source URL
   - If the source URL matches an existing framework's source, the user should be notified that the framework already exists
   - The user should be able to create the duplicate framework anyway if they still want to
- When searching for frameworks, the Name, Description, Source URL, and (if possible) some indicator of who entered the framework should be displayed.  This will facilitate sorting through "duplicates" and derivatives and make it easier for a user to find a framework in cases where multiple distinct frameworks have the same or similar names (e.g., multiple "math" frameworks from different PDFs)
