### ISSUE TITLE
Usage of CASS on load balanced environment

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CompetencyFrameworks#2]
@Lomilar Our production environment will be two windows servers load balanced (using the windows load balancer). Typically an app like CASS would be installed on both servers. 
Regarding elastic, will there be one instance that is referenced by both servers, or will there be elastic on both servers, and the contents synchronized? I recall that elastic can be configured to sync to multiple servers, but an not sure if this the approach to be used.

**Comment by Lomilar** [comment]
Elasticsearch can certainly be configured to balance across multiple servers. The CASS repository shouldn't mind this at all, however, it's not something we've tested yet.

**Comment by Lomilar** [comment]
Do note that there are some security credentials that are automatically generated on the server for various components that will need to be copied to both machines. These can be found in the root of the tomcat folder (usually, otherwise the working directory of the service that started Tomcat)

**Comment by Lomilar** [comment]
On ice until multiple servers are stood up.
