### ISSUE TITLE
Updating, Replacing, and Archiving Frameworks 

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/CompetencyFrameworks#20]
@Lomilar 

- Frameworks could be updated
- Frameworks could be replaced so the prior version should not be used/consumed
- Frameworks could be archived so prior versions can be found and compared

How are frameworks flagged to indicate? 

- An update has been made
- The framework is no longer in use but is archived
- The framework is replaced
- Etc..

I included @stuartasutton @siuc-nate in case they have some feedback on this.  Also, @cwd-mparsons because he's working with the Credential Registry group on the same issues.

**Comment by Lomilar** [comment]
**Issue 1.1:** Yes. Frameworks can be updated.
**Issue 1.2:** Yes, they can be replaced, but the old version is still accessible. See explanation below.
**Issue 1.3:** Older versions are automatically archived, but are still accessible. See explanation below.

**Issue 2.1:** A framework may refer to specific versions of competencies or the latest version, per the difference in URLs below. All current CASS tools link to other data using the 'latest version' of the competency.
**Issue 2.2:** This can be checked by comparing the framework to the latest version of the framework.
**Issue 2.3:** While there are not specific mechanisms for forwarding, a scheme could be conceived that does this (use of sameAs, for instance).

**Versioning in a nutshell:**
All objects in CASS are 'versioned'. A long form URL such as:

http://cass.credentialfinder.net/api/custom/data/schema.cassproject.org.0.2.Framework/b341b30e-ad37-472b-a5fd-36d912ca1021/1498253133757

refers to a specific version of the competency framework. Note the number at the end. This is the version number (and update timestamp). A short form URL such as:

http://cass.credentialfinder.net/api/custom/data/schema.cassproject.org.0.2.Framework/b341b30e-ad37-472b-a5fd-36d912ca1021

refers to the latest version of the framework.

The choice of which form to use is implementation specific. For a highly specific versioned credential that has renewal requirements, often one will desire the specific version of the competency, and will use the long form URL. It may become important that individuals can refer to the latest version of the competency as well, for instance, when specifying required competencies.

We can discuss this further on a call.

**Comment by siuc-nate** [comment]
@Lomilar Can this issue be closed?

**Comment by Lomilar** [comment]
Yes. There isn't any action to be taken on this thread.
