### ISSUE TITLE
Updating the CE Testing Server and Upcoming Production Server

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/CompetencyFrameworks#21]
How are server updates being handled so the server is updated incrementally as changes are made?

**Comment by Lomilar** [comment]
The installation process includes steps where a version of the software is chosen. Repeating these steps with a different version will update the software.

This is not intended for the long term. A proper update process will accompany a Windows installer in the future. Automated updates aren't currently on the feature list, is that desired, @cwd-mparsons?

**Comment by cwd-mparsons** [comment]
@Lomilar We probably do not want automatic updates in general.

**Comment by siuc-nate** [comment]
According to http://docs.cassproject.org/index.html?doc=1I5sVZFeOQxr2xvflCmusWuINKeuI9YlkTTXXXFBiQ04
It's not clear whether or not the newer versions of CASS require updating to elasticsearch 5.2. @Lomilar can you confirm?

**Comment by Lomilar** [comment]
Updated the guide. 

>  Elasticsearch versions below 5.x are not supported by 0.3.0 or ‘master’, however, they may continue to work.
>  If Elasticsearch 5.x or later is installed, use '0.3.0' and above or 'master'.

New releases are accompanied by messages from the Mailing List.
https://groups.google.com/forum/#!forum/cass-announce

**Comment by Lomilar** [comment]
CASS Windows installer and Linux installer takes care of ElasticSearch versions. OK to close.
