### ISSUE TITLE
Determine when to use an adapter to proxy requests to a third party API and when to store competencies in the CASS registry

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#22]
In order to be consistent in our approach, we need to determine when/how to store data in CASS when it's available elsewhere and when to just proxy those requests (i.e. create adapters) to those third party sources.

**Comment by Lomilar** [comment]
I recommend simply using URLs to refer to data.

All adapters and proxies and transforms _should_ have a URL endpoint that is sufficiently detailed to get down to the appropriate data. So even if its something like:

http://onetonline.com/asn/jobduties/13-2011/<ability code>

That should work as a URL. Hopefully, content negotiation can take care of making it a consistent standard.

In terms of governance, I tend to like what I think Stuart's approach is here: If it already exists, link to it, if it doesn't, do the following:
 * Try to convince them to make it linkable. (Great, they own it, it's on their website, good provenance)
 * Try to convince an organization that does this to make it linkable. (ASN)
 * Make it linkable ourselves (CASS Repository)

**Comment by siuc-nate** [comment]
How does that approach relate to our use case with O*NET?  Since their API is behind a password, would we not still need to implement something, or would this be handled entirely on their end?

**Comment by siuc-nate** [comment]
@Lomilar Can this issue be closed?

**Comment by Lomilar** [comment]
Yes, they will be using CTIDs and CER urls, as far as I know. I don't think O*NET has any canonical URLs for these items.
