### ISSUE TITLE
Create guidance page for CASS registry

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#25]
To mirror the CTDL and Registry guide pages on the credreg.net site.  It should cover topics like:

- where to put the files for your competencies on your website so they can be crawled
- how to setup content negotiation to access the data

**Comment by jkitchensSIUC** [comment]
@siuc-nate @Lomilar Here are some content and presentation topics:

About competency storing and tools
Why there's two registries
Credentials
Competencies
Tieing back to CTDL profile of ASN
Publishing competency frameworks
Upload
API
Downloading frameworks
Upload
API
Searching frameworks
API
Interoperability with other systems
CASE
Others?

@stuartasutton we need to be sure this ties back to the CTDL-ASN. You may have additional ideas for updating the tech site and presenting information in PPTs, videos etc..

**Comment by Lomilar** [comment]
We need to probably reimagine what goes into this, but it is still something that needs to be done.

**Comment by Lomilar** [comment]
@khavas

**Comment by Lomilar** [comment]
* Should have something about CaSS.

To be brainstormed.
