### ISSUE TITLE
Governance: Linking owners of records back to the authoritative source.

### ISSUE THREAD

**Issue by Lomilar** [CredentialEngine/CompetencyFrameworks#26]
In CASS, all records are owned by a component included in an SSL certificate.

To mitigate the duplication of frameworks/competencies, it is useful for records to be owned by people or organizations in a traceable linked data fashion.

This is a problem that plagues facebook accounts, twitter accounts, etc.

One method of verifying ownership of an object, and therefore validating the framework or competency is through some proof method that the owner owns the public key.

This may conflict with Workit owning all the records in CASS, as it is a delegated stewardship that may need tracking.

**Comment by stuartasutton** [comment]
In ASN, all competencies are part of a framework and all frameworks have an owner. Also, in RDF, they can all belong to the same named graph (description set).

**Comment by siuc-nate** [comment]
Addressed in #61
