### ISSUE TITLE
Load times are very long/slow

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#30]
The http://cass.credentialfinder.net/cass.example/framework.html page takes a very long time to load any data.

Is there a way to alter it to begin populating data (instead of waiting for everything and showing it all at once) and some kind of a loading indicator (such as a spinner or progress bar)?

**Comment by Lomilar** [comment]
Upgrading the server to the latest master should bring significant performance gains.

**Comment by Lomilar** [comment]
OK to close?

**Comment by siuc-nate** [comment]
It does seem to be a lot faster now.

However, Jeanne had requested some sort of loading indicator - is that something that can be added?

**Comment by Lomilar** [comment]
cassproject/cass-editor is nice and snappy and has a loading indicator. :-)
