### ISSUE TITLE
Enable ASN JSON export structure

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#32]
The framework manager needs to allow exporting a selected framework in ASN/JSON format with all data that was present when it was imported.

**Comment by stuartasutton** [comment]
@siuc-nate I thought the outcome of yesterday's call was that import and export needed to accommodate jsonld, rdf/json, turtle (N3), and possibly even RDF/XML.

**Comment by siuc-nate** [comment]
@Lomilar can you confirm whether or not this has been implemented?

**Comment by Lomilar** [comment]
A list of exports are as follows:
![image](https://user-images.githubusercontent.com/337692/35950752-dc268820-0c2c-11e8-9812-87a441d1c376.png)

cassproject/cass-editor#101 outlines additional export formats that have been requested.

**Comment by siuc-nate** [comment]
Thanks. This most likely covers it.  Closing for now.
