### ISSUE TITLE
Validation of incoming data

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#34]
What mechanism is used to validate incoming data (e.g., posting CTDL-ASN schema via the API)?  I don't believe it's JSON Schema, but is it something that can/needs to be externally provided?

**Comment by Lomilar** [comment]
Validation is not occurring on the data that is stored in the repository, however, that may change. If it does, it will validate and remove any invalid data fields using the JSON-LD Context via an 'expand' and 'compact' algorithm. Any errors will result in an error response code. It will then check for some rudimentary fields (id, type) and provide additional errors if the object is no longer valid JSON-LD.

See: https://www.w3.org/TR/json-ld-api/#compaction-algorithms

**Comment by siuc-nate** [comment]
What validation has been added to the CASS interface?

**Comment by Lomilar** [comment]
Validation has been added via input types (for dates), selectors (for URLs that can be selected) and URL validators of input fields (for URLs that can't currently be selected).

Many of the fields are freetext.
