### ISSUE TITLE
CASS search interface doesn't allow spaces

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#36]
the search bar in the top-right of the framework manager screen doesn't allow spaces to be entered.

**Comment by siuc-nate** [comment]
@Lomilar can you confirm whether or not this has been addressed?

**Comment by Lomilar** [comment]
In the cass editor:
The search phrase: `Domain 1` -- will search for `Domain OR 1`
The search phrase: `"Domain 1"` -- will search for `"Domain 1"` -- respecting the space.

Does this address it?

**Comment by siuc-nate** [comment]
I believe - and I could be wrong - that this issue was in reference to the original, vanilla CASS interface rather than the new editor-style one.  It is perhaps not as relevant in that sense.
