### ISSUE TITLE
Add last updated date to frameworks and competencies

### ISSUE THREAD

**Issue by tejaswidaruvuri** [CredentialEngine/CompetencyFrameworks#37]
External systems like WorkIt are syncing competency and framework information. We would like to have the ability to check if competency or framework information has been changed in order to sync back to our system. The presence of a last updated date would allow a process to retrieve records that have changed since the last check.

**Comment by stuartasutton** [comment]
That is no problem. The frameworks can have both Dublin Core date [created](http://purl.org/dc/terms/created) and date [modified](http://purl.org/dc/terms/modified).

**Comment by Lomilar** [comment]
Last Modified can be inferred by taking the last segment of the @id and converting it to a date (UTC millis from the epoch, I believe).

Date Created isn't so easy, but Stuart's suggestion would work. We're adding several schemata to our namespace scope in 0.3.

**Comment by cwd-mparsons** [comment]
@Lomilar The original request for a last modified date was to enable a request the equivalent of:
Select * from frameworks where lastModifiedDate > lastSyncDate
Same for competencies.

The purpose was to allow us to sync any records that had been updated since the last time a sync was run.
I don't see how the latter could be accomplished where the modified date is part of the @id property.

**Comment by Lomilar** [comment]
Got it. The 0.3 schema (latest) has all objects extending from CreativeWork, which provides https://schema.org/dateModified and https://schema.org/dateCreated and https://schema.org/datePublished. 

None of these are enforced.

**Comment by siuc-nate** [comment]
@Lomilar can you post an example or two of data with values in the dateModified field so we can verify it?

Thanks.

**Comment by Lomilar** [comment]
cassproject/CASS#42 - Sort and search of lastModified.
cassproject/cass-editor#116 - Autopopulate some schema fields.

**Comment by siuc-nate** [comment]
Sorry, I meant actual JSON documents in one of the CASS databases somewhere.

**Comment by cwd-mparsons** [comment]
@Lomilar Can this item be added to the priority list?
Should we have this issue in the cass-editor repo?

**Comment by Lomilar** [comment]
Yeah. Should be possible.

**Comment by Lomilar** [comment]
https://github.com/cassproject/cass-editor/issues/355

**Comment by Lomilar** [comment]
We already implement schema:dateModified, which does what you mention here.

I think the only difference in our perspectives could be that dateModified changes when a competency is added, removed, or rearranged.

![image](https://user-images.githubusercontent.com/337692/43263387-ff77f382-9097-11e8-9c52-f71c2e3c570d.png)

**Comment by stuartasutton** [comment]
The difference is not a big concern.

**Comment by stuartasutton** [comment]
We do, nevertheless, need to add ceasn:dateModified to the the ceasn schema.

**Comment by siuc-nate** [comment]
@stuartasutton is this issue waiting on us to do something with CTDL-ASN or is there still something for the CASS team to do here?

**Comment by stuartasutton** [comment]
No, this is us. It's a missing property from the ceasn schema.

**Comment by Lomilar** [comment]
Any issues to reference, or any followup here, @stuartasutton ?

**Comment by stuartasutton** [comment]
@Lomilar, @siuc-nate & @jkitchensSIUC, nothing beyond getting a `ceasn:dateModified` property declared. DCMI has a [`modified`](http://dublincore.org/documents/dcmi-terms/#terms-modified) and schema has [`dateModified`](https://schema.org/dateModified). Ours should be declared with a "same property as" assertion to both DCMI and Schema.org namespaces. The DCMI definition is quite adequate ("Date on which the resource was changed."). The schema.org definition is less so.

**Comment by Lomilar** [comment]
The JSON-LD Schema at http://credreg.net/ctdlasn/schema/context/json lacks an entry for dateModified. See comment from Sep 14.

I can make the change on our side first, but that will introduce an awkward looking variable into the export.

**Comment by siuc-nate** [comment]
We don't currently have a `ceasn:dateModified` property, pending or otherwise.

Would something like this work?:
>**URI**: ceasn:dateModified (or lastUpdated ?)
>**Label:** Date Modified (or Last Updated)
>**Definition:** The date on which this framework or competency was most recently modified (updated?) in some way.
>**Domain:** ceasn:CompetencyFramework, ceasn:Competency
>**Range:** xsd:date
>**Equivalent To:** schema:dateModified, dct:modified
>**Subproperty Of:** dct:date (not sure about this one)

While we're at it, it might be good to also declare ceasn:dateCreated to be Equivalent to schema:dateCreated (it's already equivalent to dct:created)

**Comment by Lomilar** [comment]
Looks good.

**Comment by siuc-nate** [comment]
Per our 10/24/2018 conversation:
Action to be taken: 

>**URI**: ceasn:dateModified
>**Label:** Date Modified
>**Definition:** The date on which this framework or competency was most recently modified in some way.
>**Domain:** ceasn:CompetencyFramework, ceasn:Competency
>**Range:** xsd:datetime
>**Equivalent To:** schema:dateModified, dct:modified
>**Subproperty Of:** dct:date

**Comment by Lomilar** [comment]
Please notify @Lomilar when this action is taken.

**Comment by siuc-nate** [comment]
The changes above have been made in pending CTDL-ASN and noted in the history tracking.

@Lomilar This goes live tomorrow.
http://credreg.net/ctdlasn/release?releaseID=20181026
