### ISSUE TITLE
ASN-based API endpoints

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#39]
I have been attempting to work with the API lately in order to build out an interface in workit to create and manage competency frameworks. I've been finding it very difficult to manage conversion back and forth between formats used by our system/interface (still in development) and the separation of nodes and relations as used in CASS (especially where it concerns moving nodes up or down in a list or changing the parent of a node from one node to another).  The signing process is proving to be difficult to debug as well.

Would it be possible to have API endpoints that allow for CRUD operations on an entire framework using the ASN schema, or some reasonable subset thereof? Even being able to include parent/child relationships on the nodes themselves rather than try to abstract that out to a separate array of objects would be a huge step forward.

I could then download (and later reupload) an entire framework after it has been interacted with in some interface, instead of trying to manage nodes and relations piecemeal as the user is doing things. Such an approach would of course need to maintain the GUIDs for each node, so that external references would not break, but otherwise it should work.

If possible, it would be nice to not require signatures on such endpoints, or to simplify that process if you have any suggestions for doing so (perhaps just including some kind of API key?).  Signing the document and then signing the POST message itself seems like overkill - we aren't transferring sensitive data, after all.

**Comment by Lomilar** [comment]
The two layers of signing (signing the HTTP request and signing the Object) provide two different features:

 * Signing the HTTP request ensures the server that the person making the request is whom they say they are (namely the owner of the object).
 * Signing the Object ensures anyone who retrieves the object that it hasn't been tampered with.

The two mechanisms ensure the object's integrity and allow per object write access.

The owner and signing stuff can be omitted, and the objects will then be editable by anyone.

Additionally, we can begin working on an oAuth based delegated authority model to move this work to the server. That's a whole different bucket of worms, of course.
If you'd like to contribute the C# code you have written for manipulating CASS objects into an OSS CASS C# library, I'd be more than happy to help flesh the signing part (and other parts) out.

**Comment by Lomilar** [comment]
Another possibility would be that we implement an API on the server that uses a server identity and an API key, similar to the previous custom service. I can focus on this documentation in the Developer Guide in order to allow you to write those API services as well. That may be a shorter path.

**Comment by Lomilar** [comment]
We continued to flesh out this approach (using a server identity to do such tasks) as part of allowing CASS to be a registry.

The Connecting Credentials ASN endpoint is demonstrated here: https://dev.cassproject.org/api/asn/8eb2d64dff5b2a84c5da255d9d18de5b

You can 'PUT or POST' to this endpoint as well and it will update the framework. No records will be deleted, only updated.

Registering frameworks is currently an open API. We can lock this down if need be for the CE use case.

This feature is now in the CASS master branch, feel free to deploy when ready.

**Comment by Lomilar** [comment]
Example (that may disappear)
https://cass.credentialengine.org/api/asn/3b0f554b-178f-4678-9885-40fc6cc9d02d

Ok to close.
