### ISSUE TITLE
Script for Importing Competency Frameworks

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/CompetencyFrameworks#4]
Fritz has code for importing competency frameworks. Determine if the code is needed to batch upload more frameworks to CASS.

**Comment by Lomilar** [comment]
Here's the script (in .txt form) used to upload the frameworks and competencies to the Dev server.

To use:
1. Install Node.js, and place it on your path.
2. Copy this text file and the CSV @cwd-mparsons sent to me into the same directory.
3. From a command line CD'd to the place where the text file and CSV are located:
4. npm install cassproject papaparse
5. node importCECompetencies.txt

[importCECompetencies.txt](https://github.com/CredentialEngine/CompetencyFrameworks/files/1043117/importCECompetencies.txt)

**Comment by tejaswidaruvuri** [comment]
Hey, while I was running through the steps, I was stuck at step 4 while installing the cassproject. I herewith attach the screenshot of the errors. 
![image](https://user-images.githubusercontent.com/27224483/27232161-99a20ca2-527a-11e7-928a-e7bbf744d6b7.png)

**Comment by Lomilar** [comment]
For reasons unknown to me, some node module we depend on requires python.

https://stackoverflow.com/questions/15126050/running-python-on-windows-for-node-js-dependencies

**Comment by tejaswidaruvuri** [comment]
It seems now the python is working. But still, the error comes up. I am not getting to know what exactly is the problem when all the dependencies exist. I worked on the link you sent too and had the installation of 
**npm install --global --production windows-build-tools**
and then to install the package
**npm install --global node-gyp**
![image](https://user-images.githubusercontent.com/27224483/27294118-11d80158-54de-11e7-95d1-f36e43798e33.png)

**Comment by jkitchensSIUC** [comment]
@tejaswidaruvuri @cwd-mparsons can't you give @Lomilar admin access to that server and meet him via a screen share to get this done?

**Comment by Lomilar** [comment]
Email sent. You may also want to see the command line script here to get NPM set up on windows: https://github.com/cassproject/CASS/blob/master/scripts/node/configureWindows.bat

**Comment by Lomilar** [comment]
Configuring node on the server proved a bit more complex than expected.

First, I attempted to follow the script here: https://github.com/cassproject/CASS/blob/master/scripts/node/configureWindows.bat

but npm was complaining of invalid references to npm-cli as Tejaswi mentioned. 
I downloaded and reinstalled node from https://nodejs.org/en/download/.

>npm install --global --production windows-build-tools
>npm -g install npm@next

both worked fine after that, but

>npm install node-jquery-xhr
>npm install node-forge
>npm install form-data
>npm install antlr4

did not. I googled the error message and found that Visual Studio build numbers needed to be set, which was accomplished by

>npm config set msvs_version 2015 --global

After that, the installs above worked.

Running the script, I noticed the CSV is not a CSV. It is likely an excel spreadsheet of some sort renamed with a csv extension, which will not work. The spreadsheet needs to be output as a CSV. Once that is done, the script should run.

**Comment by siuc-nate** [comment]
Can this issue be closed?

**Comment by cwd-mparsons** [comment]
@Lomilar 
Fritz, we now want to convert the framework and competency data in workIt to refer to the CASS URI. I don't see a straightforward approach for conversion as the data stands. We thought that the following could work:
- clear out all workIT frameworks and competencies from CASS
- redo the export from workIT, but add two new columns containing the Guid for the framework and the Guid for the competency
- use the latter Guids as part of the Uri for each entry (framework, and competency)
- assuming the import works, we can then use the constructed Uri in workIT as the CASS reference

Do you see any issues with this approach? Or do you have alternative suggestions?
