### ISSUE TITLE
Interface/Usability Issues List

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#47]
@jkitchensSIUC, @cwd-mparsons, and myself reviewed the CASS editor interface today. We have some changes:
- Edit section (right bar) should be wider
  - Ideally this should be user-resizeable
  - Should default to a percentage width with a minimum width (at least 33% default)
- Data entered in fields on the right should show in the hierarchical list on the left in a way that makes sense
- Competency Text box should be a textarea that is at least as large as the Comment box
- In Language should validate against language codes
- In Language should cascade down from the parent entity (e.g., from the framework to each competency)
- Keywords should be separable into individual strings (method TBD)
- Tooltip for "Derived From" does not display text
- Back button gets caught in a loop if you add a concept scheme and concept (cannot get back to framework/competency editor)
- Validation should not allow data to be saved if it is not valid
- Identify the acceptable file formats and schemas for the import tab
  - e.g., List JSON, CSV and ASN-DL, CTDL-ASN, CASE, etc.
- Search should look in competencies (i.e., find a framework by text within one of that framework's competencies)
- Search should look in concepts (i.e., find a framework by text of concept(s) connected to it) 
- Search list results need to show more data
- @stuartasutton we need to clarify the definition of Competency Category
- @stuartasutton we need to clarify which URI properties should resolve to data, and which can just be URLs to HTML web pages
- @stuartasutton we need to verify that the groupings and order of terms are based on your recommendations

Let us know if you have any questions.

Thanks.

**Comment by stuartasutton** [comment]
#### 1. Competency Category

The current definition:
> The textual label identifying the category of the competency as designated by the promulgating body.

Could be enhanced with "such as":

> The textual label identifying the category of the competency as designated by the promulgating body such as "Domain", "Strand", "Skill", "Knowledge".

*Note:* The current comment still refers to the ASN's `statementLabel` and should be corrected.

#### 2. URI (identifier) vs URL (locator)

##### Resolving to web page (locator)
> `license`

#####  Resolving to things (data; identifiers)

>`creator`
`derivedFrom`
`complexityLevel` (vocab)
`conceptTerm` (vocab)
`educationLevelType` (vocab)
`publisher`
`rightsHolder`
`skillEmbodied` (vocab)

**NOTE:** "Resolving to things" can be to any relevant URI on the web (e.g., an identifier in Wikidata or come controlled vocabulary elsewhere (outside the Registry) on the Web.

#### 3. Groupings and Order of Terms

Yes, we are close. See: https://github.com/cassproject/cass-editor/issues/126#issuecomment-369930926 ....and todays #48!

**Comment by Lomilar** [comment]
>- Edit section (right bar) should be wider
>  - Ideally this should be user-resizeable
>  - Should default to a percentage width with a minimum width (at least 33% default)

cassproject/cass-editor#131
>- Data entered in fields on the right should show in the hierarchical list on the left in a way that makes sense

cassproject/cass-editor#132
>- Competency Text box should be a textarea that is at least as large as the Comment box

cassproject/cass-editor#133
>- In Language should validate against language codes

cassproject/cass-editor#134
>- In Language should cascade down from the parent entity (e.g., from the framework to each competency)

Language propagates upon next edit (so if you create the framework and assign language, it will propagate to each new competency) but it isn't programmatic. If it is supposed to be programmatic, I'd recommend removing language from competency.
>- Keywords should be separable into individual strings (method TBD)

Currently delimiter based. Scoped in cassproject/cass-editor#56
>- Tooltip for "Derived From" does not display text

Addressed in cassproject/cass-editor#130
>- Back button gets caught in a loop if you add a concept scheme and concept (cannot get back to framework/competency editor)

Being addressed in cassproject/cass-editor#129
>- Validation should not allow data to be saved if it is not valid

How much validation are we looking for?
>- Identify the acceptable file formats and schemas for the import tab
>  - e.g., List JSON, CSV and ASN-DL, CTDL-ASN, CASE, etc.

cassproject/cass-editor#135
>- Search should look in competencies (i.e., find a framework by text within one of that framework's competencies)
>- Search should look in concepts (i.e., find a framework by text of concept(s) connected to it) 

This used to work. cassproject/cass-editor#136
>- Search list results need to show more data

cassproject/cass-editor#132
>- @stuartasutton we need to clarify the definition of Competency Category
>- @stuartasutton we need to clarify which URI properties should resolve to data, and which can just be URLs to HTML web pages
>- @stuartasutton we need to verify that the groupings and order of terms are based on your recommendations
