### ISSUE TITLE
Repeatability of properties needs to be enabled

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CompetencyFrameworks#48]
Currently the editors for both competencies and concepts do not handle repeatable values. If you look at the [controlling google sheet](https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1476845803) in the repeat column, you'll see that these properties are numerous. Repeatable properties should be handled by having the means to repeat the input template and **not** by devising delimiter schemes since, in all cases of literal values, a need to handle language variances is always present.

**Comment by stuartasutton** [comment]
An example of repeatability/language tag solution from the ASN angular editor:

<img width="545" alt="screen shot 2018-03-02 at 5 12 07 am" src="https://user-images.githubusercontent.com/2939046/36900903-f0d11cd6-1dd9-11e8-8213-1043fb5def95.png">

**Comment by stuartasutton** [comment]
Note that this repeatability matter affects bullet: "Keywords should be separable into individual strings (method TBD)" in issue #48. Keywords should be "separated" as individual entries in a repeatable `conceptKeyword` property and not as members of a delimited string of text.

**Comment by siuc-nate** [comment]
I'm pretty sure this works now, right?
