### ISSUE TITLE
Legacy competency framework data (2nd round)

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CompetencyFrameworks#49]
@Lomilar. @cwd-mparsons, @jkitchensSIUC, @siuc-nate: While the second round of export/import of legacy competency framework data led to additional insights, it raised as many new issues as it solved. Recognizing that no mapping from the legacy to CASS will solve all the issues, I think I see a path that will give us the most with the least hand editing. Here's a diagram and explanation showing:

 1. The legacy registry data as it is;
 2. The export of that data; and
3. The CASS import 

![2018-03-04-legacy_transfer](https://user-images.githubusercontent.com/2939046/36977469-19dc0740-2036-11e8-9f38-d88708ab941e.png)

#### What's Happening?

The editor for entering competencies has: (1) competency framework (name and source URL); & (2) competency (or array of competencies).

1. The current data in the framework field is seldom (ever?) a description of the framework. Instead, it is a description of a top-level competency node or a conflated set of top-level nodes in a framework.

2. What is happening in the 2nd export, is that the addition of the name of the framework is now overwriting the existing data in the framework name meaning loss of all that top-level competency data.

3. What needs to happen is:

  * The current framework name data needs to be transcribed/mapped over instead as a top-level competency; and
  * A new framework node created using the name of the assessment, learning opportunity or credential to which the framework is attached. 

4. The existing legacy competency is then made to point with a isChildOf property to the transcribed new competency created in 3 above. It's isPartOf is made to point to the new framework node.

5. For the next round, there should be only **one** framework node per assessment, learning opportunity or credential to which competencies are directly attached.

With no. 5 above, we may see some aggregation of several frameworks into one because of variances in how people entered the legacy data. That can be manually fixed on review.

@cwd-mparsons, if this is not absolutely clear, please speak up so we don't end up wasting your time.

**Comment by stuartasutton** [comment]
@siuc-nate, I see only one problem with the  2nd legacy upload. While there are some data issues, they are "editor" issues and not legacy upload issues.

The one error I have found in the upload is the non-aggregation of nodes for one framework. If you scan down the index, you'll see 7 frameworks with only 1 competency. All 7 belong to one framework:

1. Assessing Your Learners 
2. Connecting Learning Theories to Your Teaching Strategies
3. Creating Presence in Your Online Course
4. Evaluation of Course Design
5. Exploring Your Institutions Policies
6. Gauging Your Technology Skills
7. Orienting Your Online Learners.

https://credentialengine.org/publisher/organization/1338

<img width="1029" alt="screenshot 2018-03-29 16 20 18" src="https://user-images.githubusercontent.com/2939046/38118120-80833410-336d-11e8-9d97-018a47d23036.png">

**Comment by siuc-nate** [comment]
Can this be closed?
