### ISSUE TITLE
Setup CASS in Credential Engine Test and Staging Environments

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/CompetencyFrameworks#5]
Need to verify the setup of the CASS system on test and then copy to staging.

**Comment by Lomilar** [comment]
First thing to check: Make sure the elasticsearch service is started (and starts upon boot-up.)

**Comment by cwd-mparsons** [comment]
@Lomilar I checked and noticed (was reminded) that we already had an older version (2.0) of elastic running on that server (for another project).. We will need to review this setting.

**Comment by Lomilar** [comment]
CASS has been tested on and can run off of ElasticSearch 2.2.x as part of backwards compatibility with version 0.2. You'll be using a more experimental release.

I'm not sure how well supported 2.x will be down the line. Do you have virtualization options?

**Comment by Lomilar** [comment]
Complete. http://cass.credentialfinder.net/
