### ISSUE TITLE
Creator CTIDs should be lowercase

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#51]
I checked the [import](https://docs.google.com/spreadsheets/d/1JwXZcBQUsurWwWkq13B9aB7A_gLsfLcffwo7I9mfwaA/edit#gid=1597492267) and, unfortunately, it seems I missed the `ceasn:creator` field when lowercasing all the CTIDs.  These should be lowercased to match all the other CTID-based URIs.

@cwd-mparsons will this cause any issues on our end?

**Comment by cwd-mparsons** [comment]
@siuc-nate 
The credential registry is currently case sensitive. This would be an issue.
However, the CR team is working on making the get by resource URL case in-sensitive. This request had been requested earlier, and found that the change was 'approved', not implemented, but didn't work.
https://github.com/CredentialEngine/CredentialRegistry/pull/133

**Comment by siuc-nate** [comment]
It should be lowercase in the source data too - presumably this means republishing, which I think we were going to need to do at some point anyway (unless I'm thinking of something else)?

**Comment by siuc-nate** [comment]
It could be related, but I'm not sure how many of those creator orgs were published to begin with.

**Comment by stuartasutton** [comment]
How could we have frameworks published and their associated orgs. not?

**Comment by Lomilar** [comment]
I'd rather not re-import any longer. We can create/run a script to change creators to lowercase.

**Comment by siuc-nate** [comment]
@stuartasutton Most of the issue would stem from data that was entered in the very early days, before most of the validation and whatnot was in place.

That said, the issue seems to mostly be related to the uppercase/lowercase CTID thing instead. It _might_ explain all of the cases.

@Lomilar I believe all of the CTID data in CASS is already lowercased

**Comment by siuc-nate** [comment]
@stuartasutton @cwd-mparsons @Lomilar is there anything left for the CASS team to do here or do we just need to handle republishing the records in the registry to give them all lowercase CTIDs?

**Comment by Lomilar** [comment]
If this is being handled by CredentialEngine/CredentialRegistry#133, I'd say no, there's nothing left for the CASS team to do.

If we want to handle the problem at the source, we need to write a little script to go detect non-lowercased CTIDs and fix it, then republish from CaSS to the CER.

**Comment by siuc-nate** [comment]
This should all be working now.
