### ISSUE TITLE
Update ceasn context file for ordered lists

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CompetencyFrameworks#54]
In order to support ordered lists of competencies that are the objects of the `hasChild` and `hasTopChild` properties, we need to update the ceasn context file to include something like the following for ordered lists of competency children URIs, 

```
"hasChild": { "@id": "ceasn:hasChild","@container": "@list"},
"hasTopChild": { "@id": "ceasn:hasTopChild","@container": "@list"},
```
See related discussion at https://github.com/schemaorg/schemaorg/issues/1910#issuecomment-386204944

**Comment by siuc-nate** [comment]
This has been taken care of.
http://credreg.net/ctdlasn/schema/context/json
![image](https://user-images.githubusercontent.com/21346519/39710584-cd520986-51e2-11e8-8b50-90d6537cf291.png)

**Comment by danbri** [comment]
@stuartasutton I noticed this post via your mention within Github. If you have a view on the Schema.org proposal do please comment in our issue - this is one of those matters which is rather infrastructural and it's extra important to get lots of opinions and sanity checks...
