### ISSUE TITLE
Ceasn:category missing from json and should be part of left-hand display before ceasn:listID

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CompetencyFrameworks#56]
The `ceasn:category` property is **missing from the json export**. Second, we need to add the property to the displays of the competencies immediately before the ceasn:listID. Then, with the following json, we'd get:

>ceasn:category: "Domain"
ceasn:listID: "2"
ceasn:competencyText: "Operations"

to display as

 **"Domain 2 Operations"**

```
{
 "@id": "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/5f911c90-b0bd-4928-b380-c99c477682de/1525730785270",
            "@type": "ceasn:Competency",
           "ceasn:competencyCategory": "Domain" ,
            "ceasn:competencyText": {
                "en-us": "Operations"
            },
            "ceasn:dateCreated": "2018-05-07T22:05:54.062Z",
            "ceasn:inLanguage": [
                "en"
            ],
            "ceasn:isPartOf": "https://credentialengineregistry.org/resources/ce-35238f16-aaa7-40ef-8003-c80115870c55",
            "ceasn:listID": "2",
            "ceasn:weight": ".30",
            "ceterms:ctid": "ce-5f911c90-b0bd-4928-b380-c99c477682de"
        }
```

**Comment by Lomilar** [comment]
@stuartasutton 

There's some additional style in the stylesheet @siuc-nate may want to replicate to give it the same background as the other cells. Does this work for ya?

![image](https://user-images.githubusercontent.com/337692/40328885-bb1a09ec-5cfc-11e8-86a9-2ab7f5f0caae.png)

**Comment by stuartasutton** [comment]
Yes. This is as it should be. It's not yet live, is it? I don't see it on
records when I log in.

**Comment by Lomilar** [comment]
@siuc-nate OK to close.
