### ISSUE TITLE
URI's on competency framework & concept scheme import to CE & translation to CE-ASN

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CompetencyFrameworks#61]
@Lomilar, @siuc-nate & @jkitchensSIUC:

This issue is intended to settle any ambiguity regarding inbound partner competency frameworks and concept schemes and the treatment of URI's in the process of translation and deposit in the CER.

There are three general scenarios regarding inbound descriptions:
 
1. they have no functional URIs assigned; or
2. they have had CER namespace URIs assigned; or 
3. they have partner namespace URIs assigned.  

Bottom line, the outcome of any of these three scenarios is that, when translation is complete, all competency frameworks and concept schemes in the CER will have CER URIs (`@id`). **The concern of this issue is scenario no. 3.**  

Here's a figure regarding scenario no. 3 that's NOT intended to suggest how this data gets handled; it's just a device to illustrate. 

![2018-06-18 partner namespace uri](https://user-images.githubusercontent.com/2939046/41723378-c70dd22a-751f-11e8-9b65-194a2f90bf4d.png)

**Step 1.** Description submitted in Case with partner namespace URIs and translated into ASN with a `skos:exactMatch` inserted into each node pointing to the CER namespace URIs for that description;

**Step 2.** The ASN version with partner namespace URI's and related `skos:exactMatchs` is sent back to the partner;

**Step 3.** There is a URI swap in the ASN record so that the `@id` is now  CER namespace URI and the `skos:exactMatch` URIs point to the partner URIs; and

**Step 4.** The record with CER namespace URI is stored in the CER.

**Comment by siuc-nate** [comment]
In other words, what you end up with is:

Partner System:
```
{
  "@id": "https://partnersystemuri.org/123",
  "skos:exactMatch": [ "https://credentialengineregistry.org/resources/ce-abc" ]
}
```

CER:
```
{
  "@id": "https://credentialengineregistry.org/resources/ce-abc",
  "skos:exactMatch": [ "https://partnersystemuri.org/123" ]
}
```

Correct?

**Comment by siuc-nate** [comment]
Sounds good to me - this is what I've been pushing for all along (albeit with `sameAs`).  It allows each system to have its own "canonical" URI for the data - but it's really just the URL of that _document_ rather than some universally-accepted URI for the resource itself.  

Anyway, I'm on board with it.

**Comment by Lomilar** [comment]
Should we handle these transforms on the publisher side or the editor side?

I can see some advantages to doing it on the editor side, namely managing and being able to modify the exactMatch.

**Comment by stuartasutton** [comment]
I've deliberately not used owl:sameAs.

**Comment by siuc-nate** [comment]
I was thinking schema:sameAs, but exactMatch works fine too.

**Comment by stuartasutton** [comment]
I deliberately used skos:exactMatch because it's from a W3C specification and has massive use.

**Comment by Lomilar** [comment]
We should implement this process as soon as the data touches the cass-editor deployed in the CE.

**Comment by Lomilar** [comment]
cassproject/cass-editor#313

**Comment by stuartasutton** [comment]
Since [cassproject/cass-editor #333](https://github.com/cassproject/cass-editor/issues/333) references this issue, we can close it here. The figure at the top and accompanying text are useful.
