### ISSUE TITLE
CASS search needs to indicate what items are approved and published

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#62]
The search for competencies will need to store information about which frameworks have been approved and published, and there will need to be a way to filter based on this information.

**Comment by Lomilar** [comment]
Considering an approach where we notify the parent page when we receive search results, and provide a means of "annotating" frameworks with tags (like the XX items) so that (Approved) (Published) can be added to those (or other) framework results from the parent page.

How does that approach sound?

**Comment by siuc-nate** [comment]
The problem is that we also need to be able to filter based on this information, so it will probably have to be stored in the index somewhere. Correct me if I'm wrong.

**Comment by Lomilar** [comment]
That's sounding more and more like the publisher needs to modify the data in CASS and add meta:lastPublished and meta:lastApproved or something.

I figured we'd have to bridge this gap at some point. We can accomplish this via microservices that you call, a direct C# to JS interface, or raw C#. Any preference?

**Comment by siuc-nate** [comment]
Considering that there's already a process built into the interface to manage looking up and issuing approvals and triggering publishing, it might be easiest(?) to just add something in (on our side) that would pass something to the CASS editor via postMessage that tells CASS to mark the currently-viewed framework as approved/published.

Though having some API endpoint our system could call to do this would likely be useful as well. A simple HTTP POST passing some kind of authentication from the Publisher server to CASS (authenticated with CE keys? I'm not sure) to do that seems like it should do the trick.

One thing we should determine is what exactly the data would be - e.g., just a boolean of "isPublished" vs a DateTime of "lastPublished", or both, or implying the former by the existence/value of the latter...what seems best @Lomilar @cwd-mparsons ?

We can create whatever meta properties are necessary.

**Comment by Lomilar** [comment]
>pass something to the CASS editor via postMessage that tells CASS to mark the currently-viewed framework as approved/published.

I presume publishing will occur through more methods than the screen where the CASS editor is stationed. This should probably be a system-level operation, where we either watch the registry and mark things as published (which doesn't cover approved) or get direct event notifications when the publisher pushes buttons.

<cassEndpoint>/api/ce/approved?frameworkId=<frameworkId>
<cassEndpoint>/api/ce/published?frameworkId=<frameworkId>

Probably a password URL parameter as well. We can either have the CE admin key POSTed to the service or store it locally (bad practice).

**Comment by cwd-mparsons** [comment]
Requests to approve or publish occur in the same iframe that hosts the CASS editor. On success it should be straightforward make the agreed upon call.
We don't currently have a process to do a mass publish/republish, but is likely needed in the future. A process like this would likely have to use an API approach rather than a post message.

**Comment by Lomilar** [comment]
https://github.com/cassproject/cass-editor#filtering-frameworks-by-an-additional-search-query

**Comment by Lomilar** [comment]
https://github.com/cassproject/cass-editor#set-data-helper

**Comment by Lomilar** [comment]
First question:
It loads the object, changes it and saves it. What field do you key off of to determine whether something should be published?

Second question:
The set action would be to set it to false. If you set it to null, it may be deleted? Not sure.

**Comment by Lomilar** [comment]
Could be accomplished via https://github.com/cassproject/cass-editor#set-data-helper to set data on the CaSS object (when published, when updated, etc)

CaSS then can filter/search

**Comment by siuc-nate** [comment]
We will likely need to solve this with some sort of meta property that allows us to indicate one of these statuses:
- Draft (The user has not approved the framework yet)
- Approved (The user has signalled that the framework is ready to be published to the Registry)
- Published (The framework has been published to the Registry)

**Comment by Lomilar** [comment]
Can also be solved by HTTP Getting the registry URL and if it returns data, it is published, and we can put that in the results as a tag (similar to Editable).

**Comment by Lomilar** [comment]
Can also create a pathway where search results, as they come up, are pumped via messages.
Then, the parent page would need to be able to push a tag into a search result. (Approved mm/dd/yyyy, Published mm/dd/yyyy)

**Comment by Lomilar** [comment]
@siuc-nate @cwd-mparsons to perform a set message on the framework when a framework is published.
@Lomilar and @woodkri to put that value in a tag on the framework browse/search.

**Comment by cwd-mparsons** [comment]
@Lomilar We have an unpublish event. This method deletes the document in the registry, and sets published date to null. In this case does a set message of Published:"" essentially remove the key, or is the equivalent of a delete required?

**Comment by siuc-nate** [comment]
Would setting the value to an explicit null work?

e.g.
```
{
  "Published": null
}
```

**Comment by Lomilar** [comment]
That will set published to null, which isn't the same as deleting it, but should effectively work the same.

**Comment by cwd-mparsons** [comment]
@Lomilar HELP
I have been trying to test using setMessage - unsuccessfully. 
I used the format: 
![image](https://user-images.githubusercontent.com/26332112/63202118-e7791e00-c04d-11e9-8184-7f9522546952.png)

I was trying a couple of formats. 
![image](https://user-images.githubusercontent.com/26332112/63202151-02e42900-c04e-11e9-85b0-e56f97fe4582.png)

I first used the registry URI for _**id of the object to set**_, and got 502 errors. 
id:https://sandbox.credentialengineregistry.org/resources/ce-48776fe4-5b56-4e10-a8d6-ccd8944b081f

I then tried putting the editor url first, followed by the registry URI for the framework:

id:https://cassproject.github.io/cass-editor/index.html?user=wait&amp;link=true&amp;newObjectEndpoint=https://sandbox.credentialengineregistry.org/resources/ce-&amp;server=https://dev.cassproject.org/api/&amp;ceasnDataFields=true&amp;show=mine&frameworkId=https://sandbox.credentialengineregistry.org/resources/ce-48776fe4-5b56-4e10-a8d6-ccd8944b081f

I got a '405' error on the latter. 
As well I got: _TypeError: Cannot set property '0' of null_
![image](https://user-images.githubusercontent.com/26332112/63202331-c7962a00-c04e-11e9-91c8-c2ce6ba5c12b.png)

What am I doing wrong?

**Comment by woodkri** [comment]
The first way is correct, using the id of the object to set: id:"https://sandbox.credentialengineregistry.org/resources/ce-48776fe4-5b56-4e10-a8d6-ccd8944b081f".

The 502 errors make me think that https://github.com/cassproject/cass-editor/issues/459 might be happening again. I did notice and fix an error on our end with the "set" code, but it wouldn't have caused a 502 error.

Did you try the first way more than once and get 502 errors again? When we were having 502 issues before, saving a second time seemed to work. I'm not sure if it's the same issue or not though.

**Comment by cwd-mparsons** [comment]
@woodkri I did try several times with the Id of the object. I will get back to this later, but first:
Is this expected to be the canonical URI or the registry URI, or either?
I have easier access to the registry URII, for what its worth.

**Comment by woodkri** [comment]
@cwd-mparsons This would need to be the canonical URI since CaSS doesn't store the registry URI internally.

After some further investigation, there's something else going on with the 502 error. I'm also getting 502s when trying to export CTDL-ASN JSON-LD on dev at the moment. Will continue to investigate.

**Comment by Lomilar** [comment]
@woodkri We have something to do here I believe.
In the set method, we have `EcRepository.save(d...)` and that should probably be `repo.saveTo(d...`

Otherwise we're trying to save to the canonical location, which isn't going to work (CORS errors when I tried it)

**Comment by woodkri** [comment]
Good catch. That fixed the CORS errors I was getting earlier and I was able to successfully send a set postMessage locally.

I don't know what happened with the 502 errors but I'm able to export again now. This is what I was getting earlier:
![502 error exporting ceasn](https://user-images.githubusercontent.com/33300923/63299429-c01b8e80-c2a3-11e9-9974-5149a2233a02.PNG)

**Comment by cwd-mparsons** [comment]
I tried doing a setMessage on update of a framework. I don't get an error, but don't see that anything was updated (in search results, I don't see the lastupdated value):
![image](https://user-images.githubusercontent.com/26332112/63383059-b48e9d00-c361-11e9-818f-56ccc9476b53.png)

I am not sure if the message: Retrieved object was not a competency, was related to the set or something else. 
However, there seems to have been an endless loop triggered. The post message is sent, then a frameworkChanged message is sent, which leads to the code to do the setMessage for lastupdated, and so on .....

Competencies:503 Sending PostMessage to CASS iframe:  Object
cass-editor.js:104114 Object
Competencies:477 Received Message Object
cass-editor.js:103732 Server: http://opensalt.opened.com/ims/case/v1p0/CFDocuments/7184d8cc-02aa-11e8-b2e3-afcff7af25c6
7cass-editor.js:95401 Retrieved object was not a competency
constructor.getBlocking @ cass-editor.js:95401
cass-editor.js:103121 Object
cass-editor.js:103121 Object
Competencies:477 Received Message Object
Competencies:519 Current Framework changed Object
Competencies:477 Received Message Object
Competencies:532 Framework updated Object
Competencies:331 Response:  Object
Competencies:331 Response:  Object

Competencies:503 Sending PostMessage to CASS iframe:  Object
cass-editor.js:104114 Object
Competencies:477 Received Message Object
cass-editor.js:103732 Server: http://opensalt.opened.com/ims/case/v1p0/CFDocuments/7184d8cc-02aa-11e8-b2e3-afcff7af25c6
7cass-editor.js:95401 Retrieved object was not a competency
constructor.getBlocking @ cass-editor.js:95401
cass-editor.js:103121 Object
cass-editor.js:103121 Object
Competencies:477 Received Message Object
Competencies:519 Current Framework changed Object
Competencies:477 Received Message Object
Competencies:532 Framework updated Object
Competencies:331 Response:  Object
Competencies:331 Response:  Object

**Comment by cwd-mparsons** [comment]
Also, a duplicate framework got created somewhere along the way. The framework used for the latter post was: **ACT Holistic Framework - Critical Thinking**. I edited the latter, after save, there are now two frameworks, with one showing as having just been created: 

![image](https://user-images.githubusercontent.com/26332112/63383554-a42af200-c362-11e9-9eda-823bf13fced5.png)

**Comment by woodkri** [comment]
The set actually did work! You can see it if you do a CaSS export of the framework: https://dev.cassproject.org/api/data/9d01832e0f14230bf615e855035ac59f. The reason it's not showing up in the search results is that lastUpdated wasn't a field I added to the bubbles on the search page. I have it checking for "Approved" and "Published" but could add lastUpdated as well if that's something you want noted on the search page.

The critical thinking framework has been imported into ctitest from two different sources (frameworks.act.org and opensalt.opened.com), which is why it shows up twice. The case frameworks don't usually have a dateCreated field so I'm guessing that one is showing up as just having been created since this was the first time it was edited after import. I don't believe I ran the script on ctitest to add a date created to all the frameworks that didn't have one, just on production.

Regarding the endless loop, are you setting lastUpdated any time you get the framework changed message from CaSS? I'm wondering if dateModified would be a more useful field since CaSS updates that field when the framework changes. Setting any field would lead to the framework changed message, so I'm not sure how to avoid an infinite loop using lastUpdated.
