### ISSUE TITLE
Search page needs to show the owner of the framework

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#63]
The owner needs to be displayed as part of the search results.

**Comment by Lomilar** [comment]
Referenced issue created.

**Comment by siuc-nate** [comment]
https://github.com/cassproject/cass-editor/issues/315

**Comment by stuartasutton** [comment]
Guys, if you showed the publisher as opposed to the creator (99.9% of the time the same thing), you could just use publisherName (text). Check any of the CCO competency frameworks.

**Comment by siuc-nate** [comment]
Closing this, since it is addressed here: https://github.com/cassproject/cass-editor/issues/315
