### ISSUE TITLE
In the finder, change the competency framework URL link to go to a CASS viewer for that framework

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#65]
Currently the link goes to the data in the registry - this may be a result of a bug in the import or in the display; there is only one result so there isn't a pattern yet.  Regardless, the link should instead lead to a CASS viewer for that framework, either as a modal window, inline, or perhaps on a separate page (less preferable).

**Comment by cwd-mparsons** [comment]
The finder was updated to use the CaSS viewer to display frameworks.
