### ISSUE TITLE
The DerivedFrom property is not included in the CEASN export

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CompetencyFrameworks#66]
for example: CSP Examination, has a derived from value of:
https://www.bcsp.org/portals/0/assets/documentlibrary/csp-complete-guide.pdf
This doesn't appear in the export:
https://cass.credentialengine.org/api/ceasn/6beada08995d6d51f87536cc8afb38c4

And so will not be published to the registry:
https://credentialengineregistry.org/resources/ce-c1bf3e36-d4f4-4522-a045-a0d6256fe131

**Comment by stuartasutton** [comment]
@cwd-mparsons, @siuc-nate, @Lomilar 

 Michael, a couple of things. 

1. This is one of the BCSP competency frameworks. BCSP actually created full-blown competency frameworks that we will be ready to load into CASS once issue #61 is complete. We need to talk about how that can be done when Nate and Fritz have the issue resolved. THEN you and I need to talk about how to keep the URIs in the credential record aligned with the competency framework URI.

2. If you mean the [ceasn:derivedFrom](http://purl.org/ctdlasn/terms/derivedFrom) property, note that it is used only "required if available" by **third parties** when they clone and then update a framework:

>"A third party version of the entity being reference that has been modified in meaning through editing, extension or refinement."

It should have a [ceasn:source](http://purl.org/ctdlasn/terms/source) URI of [framework](https://www.bcsp.org/Portals/0/Assets/DocumentLibrary/CSP-Blueprint.pdf). Your URI points to the certification as a whole.

**Comment by Lomilar** [comment]
Checking my understanding...

http://credreg.net/ctdlasn/terms/derivedFrom 
Has Competency or CompetencyFramework as the range of values.

As mentioned, ceasn:source should refer to the framework in document form.

@cwd-mparsons You did point out correctly that derivedFrom doesn't make it into the export. That has been remedied. 

Please also note: In the spreadsheet, plurallity of that value is false, but on the ctdlasn terms page, it is a multi-value. We are currently following the spreadsheet, so it is singular in the export.

**Comment by stuartasutton** [comment]
1. Yes, Competency or CompetencyFramework are the ranges for derivedFrom (for use by 3rd parties for 3rd party "versions") 
2. The ceasn:source property identifies a resource from with the CER data representation is based and against which it can be verified. Note that it is not the URL of the website where the data can be found or the credential URL etc. It is an actual page where the data can be unambiguously verified as THE framework.
3. The property should be singular.

**Comment by siuc-nate** [comment]
>Note that it is not the URL of the website where the data can be found 
Which property would capture this?

**Comment by stuartasutton** [comment]
OK, I need to be more explicit. We want, as much as possible, to stop people from doing what is convenient and get the person as close as possible to the place where they can verify. Let me give you an example of a BAD use: https://www.theboc.info/building-operator-training/course-descriptions/. I challenge you or anyone else to go here and "find" the competencies.  Try it.

**Comment by siuc-nate** [comment]
I understand that and agree - I am simply asking (as a bit of a tangent to the main issue at hand, admittedly) which property would capture the URL you reference, given that we have, so far, refused to add `subjectWebpage` (or some equivalent) to the schema. My understanding was that `source` _was_ the property intended to capture that, but that seems to be incorrect.

**Comment by stuartasutton** [comment]
Nate, I don't think we are on the separate pages.  The underlying property is ceasn:source which is quite explicit in terms of what it identifies...the actual framework and not just a subject webpage that describes it. You could say `ceasn:source` is a kind of subtype of `ceterms:subjectWebpage`.

**Comment by siuc-nate** [comment]
So if I wanted to capture https://www.theboc.info/building-operator-training/course-descriptions/ in my framework's data, would I put it in `source` or leave it out entirely?

**Comment by stuartasutton** [comment]
Quite frankly, it should be left out. Why send people there to only sit there and scratch their heads. The only way you could send them to a page where they see the actual "source" of the competencies is to the pages within courses (learning opportunities) where they can be found, e.g.:

https://www.theboc.info/courses/boc-1001/
https://www.theboc.info/courses/boc-1002/
https://www.theboc.info/courses/boc-1003/
https://www.theboc.info/courses/boc-1004/
https://www.theboc.info/courses/boc-1005/
https://www.theboc.info/courses/boc-1006/

Etc. This harkens back to https://github.com/CredentialEngine/vocabularies/issues/533 and the matter where **many frameworks** from courses have been rolled up into a single list of competencies, i.e., **one framework**--there is no place to point as source!

**Comment by siuc-nate** [comment]
Okay, that helps.  If the URL isn't useful _at all_, then it does make sense to leave it out.  But let's say I have the URL of an HTML page that does list the framework on it in some useful way, or of a PDF that contains the framework either exclusively or with other frameworks - would I use `source` for those URLs or leave them out?

**Comment by stuartasutton** [comment]
Nate, we have to fall back on what's called "the rule of reason" in law which says, in this case, that the URL is provided if the average 'Joe' would find it useful in verifying the comeptencies. I'd say that Joe would find a URL to a concise certification that clearly, clearly provides the competencies in the CER so they could be verified if this was the URL: http://nccco.org/nccco/certification-programs/mobile-crane-operator/exam-outline.

**Comment by stuartasutton** [comment]
The BOC framework where I found this https://www.theboc.info/building-operator-training/course-descriptions/ is not one of those cases where a reasonable 'joe' would find it useful.

**Comment by stuartasutton** [comment]
The average Joe looking at a BOC certification would not find this useful: https://www.theboc.info/building-operator-training/course-descriptions/
