### ISSUE TITLE
Need more permissive date validation in competency framework editor

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CompetencyFrameworks#69]
Currently, the `dateValidFrom` and the `dateValidUntil` properties require both date and time stamp. They need their validation relaxed to allow entry of date with or without time stamp. 

<img width="598" alt="screenshot 2018-07-03 12 57 39" src="https://user-images.githubusercontent.com/2939046/42241819-bb0d64d6-7ec0-11e8-8322-3195e5210fa6.png">

**Comment by Lomilar** [comment]
https://github.com/cassproject/cass-editor/issues/217
