### ISSUE TITLE
Problem translating JSON-LD to RDF in competency framework data

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CompetencyFrameworks#71]
I have run into a jsonld-2-RDF translation problem. I downloaded the CASS encoding for the "CCO Service Truck Crane Operator Written Exam" competency framework. Below I have included the snippets of json-ld encoding causing the problem followed by an rdf/turtle translation of the json-ld and an rdf/xml translation. The json-ld validates, but the two  properties in the json-ld translate to blank nodes in both the rdf/xml and the rdf/turtle. The only thing that distinguishes them from other properties in the json-ld instance is the fact that they both rely on language maps functionality **and** arrays. 

Beyond those observations, I'm stumped...

## JSON-LD
```
"ceasn:conceptKeyword": [
      {
          "en-us": [
            "service truck crane",
            "ASME B30.5",
            "OSHA 1910.180",
            "OSHA 1926 Subpart CC",
            "SAE 765A"
          ]
     }
 ],
"ceasn:publisherName": [
        {
          "en-us": "National Commission for the Certification of Crane Operators (NCCCO)"
        }
      ],
```
## Translated to RDF/Turtle

```
ceasn:conceptKeyword [ ] ;
ceasn:publisherName [ ] ;
```
## Translated to RDF/XML

```
<ceasn:conceptKeyword rdf:nodeID="genid1"/>
<ceasn:publisherName rdf:nodeID="genid6"/>
```

**Comment by stuartasutton** [comment]
No, it's not the translator. 

I went back to the language examples in the [JSON 1.1 documentation](https://json-ld.org/spec/latest/json-ld/#language-indexing) and with a minor change in the example `@context` to match the form of the offending property declaration in our `@context`, I replicated the error. 

I am uncertain how to interpret the change, so all I can do is document it.

## Original Example 73 code:

```
{
  "@context": {
    "vocab": "http://example.com/vocab/",
    "label": {
      "@id": "vocab:label",
      "@container": "@language"
    }
  },
  "@id": "http://example.com/queen",
  "label": {
    "en": "The Queen",
    "de": [ "Die Königin", "Ihre Majestät" ]
  }
}
```

#### Turtle Translation result--correct:
```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix vocab: <http://example.com/vocab/> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.com/queen> vocab:label "Die Königin"@de,
       "Ihre Majestät"@de,
       "The Queen"@en .
```

## Revised Example 73 code revised to match our data:

In our `@context`, the form of the declarations for the two offending properties are:
```
"ceasn:conceptKeyword": {"@container": "@language"},
"ceasn:publisherName": {"@container": "@language"},
```
So, below, in the Example 73 code, I changed the form of the `@context` declaration from what you see above to match the form of the offending properties in our `@context`.

```
{
  "@context": {
    "vocab": "http://example.com/vocab/",
    "label": { "@container": "@language" }
  },
  "@id": "http://example.com/queen",
  "vocab:label": {
    "en": ["The Queen"],
    "de": [ "Die Königin", "Ihre Majestät" ]
  }
}
```

#### Translation result--empty bNode:

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix vocab: <http://example.com/vocab/> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.com/queen> vocab:label [ ] .
```

**Comment by siuc-nate** [comment]
Wow, does it _really_ need to have a redundant `@id` declaration to work? That's like saying "for this thing, this thing is itself."

Or am I missing something?

**Comment by stuartasutton** [comment]
Nate, as I said, I can't explain the behavior, I just wrote down my debugging path. Earlier this afternoon I was just going to ask Gregg Kellogg what was going on but thought I'd try the little debugging experiment above. I can still ask if it appears to be a big problem. We might just try the `@context` change on those two properties and see if it actually cures the problem.

**Comment by Lomilar** [comment]
In this example:
```json
{
  "@context": {
    "vocab": "http://example.com/vocab/",
    "label": { "@container": "@language" }
  },
  "@id": "http://example.com/queen",
  "vocab:label": {
    "en": ["The Queen"],
    "de": [ "Die Königin", "Ihre Majestät" ]
  }
}
```
label is not the same property as vocab:label.
The following also works.
```
{
  "@context": {
    "vocab": "http://example.com/vocab/",
    "vocab:label": { "@container": "@language" }
  },
  "@id": "http://example.com/queen",
  "vocab:label": {
    "en": ["The Queen"],
    "de": [ "Die Königin", "Ihre Majestät" ]
  }
}
```

**Comment by siuc-nate** [comment]
`ceasn:conceptKeyword` and `ceasn:publisherName` are both marked with `@container: @language` in the context:
http://credreg.net/ctdlasn/schema/context/json

![image](https://user-images.githubusercontent.com/21346519/42383237-4f6d5c34-80fc-11e8-9484-cabf4314be53.png)
![image](https://user-images.githubusercontent.com/21346519/42383266-5d07eac6-80fc-11e8-84a8-8d99b72ec4c5.png)

So it should already be working. It corresponds to Fritz's example:
```
{
  "@context": {
    "vocab": "http://example.com/vocab/",
    "vocab:label": { "@container": "@language" } <-- This part
  },
  "@id": "http://example.com/queen",
  "vocab:label": {
    "en": ["The Queen"],
    "de": [ "Die Königin", "Ihre Majestät" ]
  }
}
```

**Comment by Lomilar** [comment]
It doesn't quite correspond to my example (apologies for not reading up the conversation)

Reducing the sample...

```json
{
  "@context": "http://credreg.net/ctdlasn/schema/context/json",
  "@graph": [
    {
      "@id": "https://credentialengineregistry.org/resources/ce-c63cbc21-b6aa-4667-8b54-672796520345",
      "@type": "ceasn:CompetencyFramework",   
      "ceasn:conceptKeyword": [
        {
          "en-us": [
            "service truck crane",
            "ASME B30.5",
            "OSHA 1910.180",
            "OSHA 1926 Subpart CC",
            "SAE 765A"
          ]
        }
      ]
    }
  ]
}
```
results in the _bnode
```
<https://credentialengineregistry.org/resources/ce-c63cbc21-b6aa-4667-8b54-672796520345> <http://purl.org/ctdlasn/terms/conceptKeyword> _:b0 .
<https://credentialengineregistry.org/resources/ce-c63cbc21-b6aa-4667-8b54-672796520345> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/ctdlasn/terms/CompetencyFramework> .
```
whereas (Note that ceasn:conceptKeyword's value is no longer an array, it's an object)
```json
{
  "@context": "http://credreg.net/ctdlasn/schema/context/json",
  "@graph": [
    {
      "@id": "https://credentialengineregistry.org/resources/ce-c63cbc21-b6aa-4667-8b54-672796520345",
      "@type": "ceasn:CompetencyFramework",   
      "ceasn:conceptKeyword": {
        "en-us": [
          "service truck crane",
          "ASME B30.5",
          "OSHA 1910.180",
          "OSHA 1926 Subpart CC",
          "SAE 765A"
        ]
      }
    }
  ]
}
```
results in 
```
<https://credentialengineregistry.org/resources/ce-c63cbc21-b6aa-4667-8b54-672796520345> <http://purl.org/ctdlasn/terms/conceptKeyword> "ASME B30.5"@en-us .
<https://credentialengineregistry.org/resources/ce-c63cbc21-b6aa-4667-8b54-672796520345> <http://purl.org/ctdlasn/terms/conceptKeyword> "OSHA 1910.180"@en-us .
<https://credentialengineregistry.org/resources/ce-c63cbc21-b6aa-4667-8b54-672796520345> <http://purl.org/ctdlasn/terms/conceptKeyword> "OSHA 1926 Subpart CC"@en-us .
<https://credentialengineregistry.org/resources/ce-c63cbc21-b6aa-4667-8b54-672796520345> <http://purl.org/ctdlasn/terms/conceptKeyword> "SAE 765A"@en-us .
<https://credentialengineregistry.org/resources/ce-c63cbc21-b6aa-4667-8b54-672796520345> <http://purl.org/ctdlasn/terms/conceptKeyword> "service truck crane"@en-us .
<https://credentialengineregistry.org/resources/ce-c63cbc21-b6aa-4667-8b54-672796520345> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/ctdlasn/terms/CompetencyFramework> .
```
which means that this is a problem with the export.

**Comment by stuartasutton** [comment]
Bloody! I didn't notice that. Thanks, Fritz. A bullet dodged.

**Comment by stuartasutton** [comment]
A cassproject/CASS commit has solved this problem.
