### ISSUE TITLE
Handling concept schemes currently defined in CTDL in CASS

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CompetencyFrameworks#72]
Currently, we have 18 SKOS concept schemes supporting CTDL credential descriptions, one of which is already being use as a controlled vocabulary for Competency Frameworks (e.g., [AudienceLevel](http://purl.org/ctdl/terms/AudienceLevel) in the Connecting Credentials framework and in the BCSP frameworks). Others in the list of 18 vocabularies below could also be of external service. Recall that success is judged more by others linking to us than by our links out to others (google axiom).

Transitioning these vocabularies to CASS as SKOS `ConceptScheme` raises at least 4 issues:

1. Settling on a single `@context` file (currently, there are 2 and these vocabularies use terms from other vocabularies). Currently, the SKOS terms are folded into the CTDL `context` and incomplete. The `context` should cover the entire SKOS terms set (it's not large).

2. SKOS concepts in the CTDL share the same history notation process as do CTDL terms. Should this practice be continued? I think so since the process we use for CTDL terms change history and concept change history is based on the settled mechanism used by the Library of Congress for change history.

3. How do we handle the transition while retaining existing URIs etc.?

4. When can this go live so that the current CASS competency framework editor can access the vocabularies during editing and the external world can explore them?

The CTDL instances of skos:ConceptScheme are:

>[ActionStatus](http://purl.org/ctdl/terms/ActionStatus) 
[AgentSector](http://purl.org/ctdl/terms/AgentSector) 
[AgentServiceType](http://purl.org/ctdl/terms/AgentServiceType)
[AssessmentMethod](http://purl.org/ctdl/terms/AssessmentMethod) 
[AssessmentUse](http://purl.org/ctdl/terms/AssessmentUse) 
[Audience](http://purl.org/ctdl/terms/Audience) 
[AudienceLevel](http://purl.org/ctdl/terms/AudienceLevel) 
[ClaimType](http://purl.org/ctdl/terms/ClaimType)
[CostType](http://purl.org/ctdl/terms/CostType)
[CredentialStatus](http://purl.org/ctdl/terms/CredentialStatus) 
[CreditUnit](http://purl.org/ctdl/terms/CreditUnit) 
[Delivery](http://purl.org/ctdl/terms/Delivery) 
[ExternalInput](http://purl.org/ctdl/terms/ExternalInput) 
[IntendedPurpose](http://purl.org/ctdl/terms/IntendedPurpose) 
[LearningMethod](http://purl.org/ctdl/terms/LearningMethod) 
[OrganizationType](http://purl.org/ctdl/terms/OrganizationType) 
[Residency](http://purl.org/ctdl/terms/Residency) 
[ScoringMethod](http://purl.org/ctdl/terms/ScoringMethod)

**Comment by siuc-nate** [comment]
Are you saying we remove the concept schemes from the schema management system and host them exclusively in CASS?

**Comment by stuartasutton** [comment]
No, you should not jump to that conclusion. But, as SKOS concept schemes, they should be managed through the concept editor and should at a minimum show up in CASS when users of the CASS editor need to assign values from them.

**Comment by siuc-nate** [comment]
If they're managed through the concept editor, does that make CASS the authoritative source/host for the data?

**Comment by stuartasutton** [comment]
What's the answer to those questions with competency frameworks?

**Comment by siuc-nate** [comment]
I know it's not authoritative for others' competency frameworks, but CASS for all intents and purposes is our system, on the same level as the scheme management system. I'm asking whether the data in CASS will be duplicated with the data in the schema management system and thus have to be maintained in addition to it, or whether it will be moved to CASS and removed from the schema management system so as to enable the "transition" to CASS and "management" in CASS that you're talking about.

If all you mean is we just need a copy of the CTDL concept schemes in CASS then that is a very different thing that would be easy to do.  I wouldn't call it a "transition" to CASS, nor would I refer to it as "management" via CASS though - that implies things that are apparently(?) incorrect, at least on a technical level.

**Comment by Lomilar** [comment]
We can put the concept schemes in CaSS in such a way that they aren't editable. That way CaSS can use them but nobody can edit them or publish them.

All that would be left would be publishing from the schema management system to CaSS as well as the registry.
