### ISSUE TITLE
Problem with competency editor

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CompetencyFrameworks#75]
On https://credentialengine.org/publisher/competencies, I am getting the following on the production server when accessing competencies:

<img width="2560" alt="screenshot 2018-11-12 13 25 16" src="https://user-images.githubusercontent.com/2939046/48376206-0ee62900-e67f-11e8-8cdd-e3189d119c03.png">

It flashes for a brief moment and then nothing but an empty window. This not a new problem. We saw it many months ago.

**Comment by cwd-mparsons** [comment]
Make that the TEST server



Michael Parsons

Sent from my smartphone


-------- Original message --------
From: Michael Parsons <CWD-mparsons@ad.siu.edu>
Date: 11/12/18 4:57 PM (GMT-06:00)
To: CredentialEngine/CompetencyFrameworks <reply@reply.github.com>, CredentialEngine/CompetencyFrameworks <CompetencyFrameworks@noreply.github.com>, Fritz Ray <fritz.ray@eduworks.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [CredentialEngine/CompetencyFrameworks] Problem with competency editor (#75)

A similar error occurs on the that server.



Michael Parsons

Sent from my smartphone


-------- Original message --------

**Comment by cwd-mparsons** [comment]
A similar error occurs on the that server.



Michael Parsons

Sent from my smartphone


-------- Original message --------

**Comment by cwd-mparsons** [comment]
This has been resolved.
