### ISSUE TITLE
Enable third-party publishing via CASS interface

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#78]
Potential workflow:
- User loads CASS editor via iframe in the Publisher site (existing process)
- Publisher checks to see if the user is associated with one or more organizations that are authorized to publish competencies (existing process)
- The user selects their organization, or their organization is auto-selected if they are only a member of one organization (existing process)
- Publisher checks to see if that organization has third-party publishing access for any other organizations (new process)
- Enable the user to select their own organization (that they are directly a member of) or one of the third-party recipient organizations (new process)
- Pass the keys belonging to the selection (either the user's own org or the third party recipient) to CASS (modification of existing process)
- CASS receives keys and continues as normal (existing process)

Note: This means that there would be nothing to indicate to CASS that there is a third-party publisher using the system, but, it probably doesn't need to know or care about that.

@Lomilar @stuartasutton @cwd-mparsons  Thoughts?

**Comment by Lomilar** [comment]
This makes sense to me. Are there any pitfalls here that you know of?
