### ISSUE TITLE
Requirements for Concept Schemes managed in CaSS

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CompetencyFrameworks#83]
@Lomilar @stuartasutton @siuc-nate 
We have identified some priority tasks related to concept schemes:

- To searchable from the opening view
- To be able to create a new Concept Scheme from the opening view
- To be able to export a Concept Scheme in @graph format, including all concepts. Currently the export is different in the dev environment and production, and we cannot export all concepts with a concept scheme.
- to be able to interact with the concept schemes in the CaSS editor from the publisher as we currently do with competency frameworks (that is for approvals and publishing. This may be straight-forward once we are able to access the concept schemes as a top level document.

There are some Concept Scheme related github issues that have been languishing:
- Need concept export of entire scheme and graph: https://github.com/cassproject/cass-editor/issues/77
- Accessibility of ceterms concept schemes to CASS editor: https://github.com/cassproject/cass-editor/issues/104
- CSV import of Concept Schemes: https://github.com/cassproject/cass-editor/issues/378

I believe that we should create a project (in github) to clearly define the work activities for enabling concept schemes as top level objects in CaSS, and define a timeline. This would appear to be a high priority for us? @jkitchensSIUC 

@Lomilar I added this issue here rather than in the CaSS editor repo in order to first identify the components, and to separate this task from other CaSS related tasks/issues that have been recently identified.
https://docs.google.com/spreadsheets/d/12j0r-buvEnKeATYBuZ1DkjDU3zpJZwbqAdpp3LXQy_0/edit#gid=1281496242

**Comment by stuartasutton** [comment]
We also need to keep in mind with these requirements, the enabling of minimum data requirements for both Concept Schemes and Competency Framework (see https://github.com/CredentialEngine/vocabularies/issues/567). Currently, almost none of the competency frameworks come even close to meeting the requirements.
