### ISSUE TITLE
"Credentials that Reference this Framework" not working

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CompetencyFrameworks#84]
@siuc-nate, the function that provides data for "Credentials that Reference this Framework" is not working. From the Credential Finder, see the image below for one of the crane operator competency frameworks that have certifications.

<img width="1255" alt="screenshot 2019-01-24 09 02 22" src="https://user-images.githubusercontent.com/2939046/51695422-e308ed00-1fb7-11e9-9b93-15b49f2968d3.png">

**Comment by siuc-nate** [comment]
This is working now:
https://credentialfinder.com/competencyframework/ce-3e21c72d-22cb-4df6-9cf7-3f00e31e3eab/
