### ISSUE TITLE
complexityLevel missing from framework export

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#86]
The beta connecting credentials framework properly shows in the CASS editor:
https://credentialengine.org/publisher/Competencies

It correctly indicates/links to the relevant concepts from the Beta Connecting Credentials levels concept scheme.  It does so via the `ceasn:complexityLevel` property - however, this property is missing from the export:
https://cass.credentialengine.org/api/ceasn/ba13a98298ab5fea4188f4bd3dacdc66

In addition, `ceasn:competencyCategory` is empty.

This fix is **urgently** needed for next week's presentation.

**Comment by stuartasutton** [comment]
Nate, the ceasn:competencyCategory issue is because competency has a capital C. Fritz caught it and It was corrected in github.

**Comment by siuc-nate** [comment]
Good, but, we still need complexityLevel up and running.

**Comment by stuartasutton** [comment]
Yup

**Comment by Lomilar** [comment]
cassproject/cass-editor#474 has updates to this.
