### ISSUE TITLE
User should be able to create and edit concept schemes within the publisher.

### ISSUE THREAD

**Issue by Lomilar** [CredentialEngine/CompetencyFrameworks#89]

**Comment by Lomilar** [comment]
https://cass.credentialengine.org/cass-editor/index.html?editorRoot=/cass-editor/&server=https://cass.credentialengine.org/&ceasnDataFields=true&webSocketOverride=wss://cass.credentialengine.org:8080/ws/custom&newObjectEndpoint=https://credentialengineregistry.org/resources/ce-&origin=https://credentialengine.org&css=https://credentialengine.org/publisher/Style/CassStyles&concepts=true

**Comment by cwd-mparsons** [comment]
complete
