### ISSUE TITLE
Hosting Concept Schemes (Vocabularies)

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/CompetencyFrameworks#9]
Are concept schemes that need to be hosted, see ASN examples on this page http://www.achievementstandards.org/content/technical-documentation under Schemes e.g., ASN U.S. Subject/Topic Vocabulary (SKOS Encoding) - This vocabulary of learning area subjects is intended to provide a uniform categorization of U.S. achievement standards.

Are these types of vocabularies, Stuart has an example now from the DQP Beta Framework for Levels, hosted in CASS or are they hosted on credreg.net?

**Comment by stuartasutton** [comment]
Since CASS can handle it, should be there.

**Comment by Lomilar** [comment]
Jeanne mentioned you had some example SKOS files. Can I get those in order to perform an import so we can discuss the tools that need to be built to support SKOS use cases?

**Comment by stuartasutton** [comment]
@Lomilar, I have one external vocabulary (beta Credential Levels) attached but would like to get the namespace ironed out with them before we practice with it. It's in resource-centric (rdf) json and generated with our SKOS editor (http://rdf.tools) with preliminary URI. 

BUT, we actually have 19 SKOS vocabularies in the context of the CTDL in json listed at http://www.credreg.net/ctdl/schema that you can use to build SKOS support. They have some properties in their document descriptions that might not be necessary that we could discuss.

```
Agent Sector
Agent Service Type
Assessment Method
Assessment Use
Audience
Audience Level
Claim Type
Cost Type
Credential Status
Credit Unit
Delivery Type
External Input
Intended Purpose
Learning Method
Organization Type
Residency 
Scoring Method

Ignore Person Type
```
[ConnectingCredentialsLevels.txt](https://github.com/CredentialEngine/CompetencyFrameworks/files/1067993/ConnectingCredentialsLevels.txt)

**Comment by stuartasutton** [comment]
The Connecting Credentials has a .txt extension because github doesn't seem to handle the json extension.

**Comment by siuc-nate** [comment]
We would need to ensure these are properly differentiated from competencies.  Perhaps a mechanism akin to the "communities" feature of the credential registry, or a special type of relation would work?

**Comment by stuartasutton** [comment]
Yes, it would be necessary to differentiate between competency frameworks (ASN) and concept schemes (SKOS) both in terms of what people can search for and browse and in the form of output

**Comment by stuartasutton** [comment]
@Lomilar, we also have 8 competency frameworks from the BCSP (Board of Certified Safety Professionals). These would need to be there as test files since there are tweaks to be done before finalized and http-based URIs as opposed to urn-uuid URIs.
