### ISSUE TITLE
CTITest Organization -- no longer can edit frameworks associated with our org?

### ISSUE THREAD

**Issue by Lomilar** [CredentialEngine/CompetencyFrameworks#90]
On CTITest, the Eduworks organization seems to have the Competency Framework permission but doesn't show up in the list of organizations that our users can edit.

Affected:
Me, Kristin, Eddie

@woodkri @eddavies @siuc-nate @cwd-mparsons

**Comment by cwd-mparsons** [comment]
@Lomilar Sorry I had updated the test server without removing some 'temporary' settings that I was using for other testiing. 
You now see all of the eduworks frameworks.
